USE ROLE SYSADMIN;
EXECUTE IMMEDIATE $$
DECLARE
  invalid_confirmation EXCEPTION (-20005, 'Set RR_CONFIRM to TEARDOWN before removing the demo.');
  invalid_target EXCEPTION (-20003, 'Target mismatch. Set RR_EXPECTED_ACCOUNT to the intended ORGANIZATION.ACCOUNT.');
BEGIN
  IF ($RR_EXPECTED_ACCOUNT IS NULL OR UPPER($RR_EXPECTED_ACCOUNT) <> (CURRENT_ORGANIZATION_NAME() || '.' || CURRENT_ACCOUNT_NAME())
      OR CURRENT_ACCOUNT_NAME() ILIKE '%SNOWHOUSE%') THEN RAISE invalid_target; END IF;
  IF ($RR_CONFIRM IS NULL OR $RR_CONFIRM <> 'TEARDOWN') THEN RAISE invalid_confirmation; END IF;
END;
$$;
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.DEPLOY_ASSETS(VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.SEED_DEMO();
DROP AGENT IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.RESTAURANT_RECOVERY_AGENT;
DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_RESTAURANT_RECOVERY_PERFORMANCE;
DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_RESTAURANT_RECOVERY_OPERATIONS;
DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_RESTAURANT_RECOVERY_COMPARISONS;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.COMPARISON_EVIDENCE;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.WINDOW_OUTCOMES;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.PEER_SELECTION;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.PRE_PERIOD_FEATURES;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.ANALYSIS_WINDOWS;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.OPERATIONS_EVIDENCE;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.PAIRED_PERFORMANCE;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.PERFORMANCE;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.OPERATIONS;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.EVENTS;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.CALENDAR;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.ROSTER;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.RELEASE_METADATA;
DROP FILE FORMAT IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.CSV_INPUT;
DROP STAGE IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.RELEASE_FILES;
DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY RESTRICT;
DROP WAREHOUSE IF EXISTS SFE_RESTAURANT_RECOVERY_WH;
USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS SFE_RESTAURANT_RECOVERY_READER;