USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_EXAMPLE
  COMMENT = 'Shared SE demonstration database';
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS
  COMMENT = 'Shared semantic views for SE demonstrations';
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY
  COMMENT = 'DEMO: Synthetic restaurant recovery (Expires: 2026-10-22)';
CREATE WAREHOUSE IF NOT EXISTS SFE_RESTAURANT_RECOVERY_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE STATEMENT_TIMEOUT_IN_SECONDS = 120
  COMMENT = 'DEMO: Restaurant recovery compute (Expires: 2026-10-22)';
USE WAREHOUSE SFE_RESTAURANT_RECOVERY_WH;
CREATE STAGE IF NOT EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.RELEASE_FILES
  COMMENT = 'DEMO: Versioned fictional source files and skills (Expires: 2026-10-22)';
CREATE FILE FORMAT IF NOT EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.CSV_INPUT
  TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' EMPTY_FIELD_AS_NULL = TRUE
  COMMENT = 'DEMO: Restaurant recovery CSV input (Expires: 2026-10-22)';
CREATE TABLE IF NOT EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.ROSTER (
  RELEASE_ID VARCHAR, RESTAURANT_ID VARCHAR, RESTAURANT_NAME VARCHAR, MARKET VARCHAR,
  FORMAT VARCHAR, OPEN_DATE DATE, CLOSE_DATE DATE
) COMMENT = 'DEMO: Fictional restaurant roster (Expires: 2026-10-22)';
CREATE TABLE IF NOT EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.CALENDAR (
  RELEASE_ID VARCHAR, BUSINESS_DATE DATE, BASELINE_DATE DATE, WEEK_START DATE, COMPLETE BOOLEAN
) COMMENT = 'DEMO: Explicit synthetic business calendar (Expires: 2026-10-22)';
CREATE TABLE IF NOT EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.PERFORMANCE (
  RELEASE_ID VARCHAR, RESTAURANT_ID VARCHAR, BUSINESS_DATE DATE, DAYPART VARCHAR,
  CHANNEL VARCHAR, GUESTS NUMBER(18,0), CHECKS NUMBER(18,0), NET_SALES NUMBER(18,2), COMPLETE BOOLEAN
) COMMENT = 'DEMO: Fictional daily guest occasions, checks and net USD sales (Expires: 2026-10-22)';
CREATE TABLE IF NOT EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.OPERATIONS (
  RELEASE_ID VARCHAR, RESTAURANT_ID VARCHAR, BUSINESS_DATE DATE, DAYPART VARCHAR,
  OPEN_HOURS NUMBER(10,2), LABOR_HOURS NUMBER(10,2), SERVICE_MINUTES NUMBER(10,2),
  SERVICE_OBSERVATIONS NUMBER(18,0), COMPLETE BOOLEAN
) COMMENT = 'DEMO: Daily operations; never repeat hours across channels (Expires: 2026-10-22)';
CREATE TABLE IF NOT EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.EVENTS (
  RELEASE_ID VARCHAR, EVENT_ID VARCHAR, RESTAURANT_ID VARCHAR, EFFECTIVE_DATE DATE,
  DAYPART VARCHAR, EVENT_TYPE VARCHAR, SOURCE VARCHAR
) COMMENT = 'DEMO: Fictional dated events; not causal labels (Expires: 2026-10-22)';
CREATE TABLE IF NOT EXISTS SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.RELEASE_METADATA (
  RELEASE_ID VARCHAR, AS_OF_DATE DATE, CONTRACT_VERSION VARCHAR, ANALYSIS_VERSION VARCHAR,
  SYNTHETIC BOOLEAN, SEED NUMBER(18,0)
) COMMENT = 'DEMO: Release provenance (Expires: 2026-10-22)';