USE WAREHOUSE SFE_RESTAURANT_RECOVERY_WH;
USE SCHEMA SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY;

CREATE OR REPLACE VIEW PAIRED_PERFORMANCE COPY GRANTS
COMMENT = 'DEMO: Observed paired cells; nulls stay excluded (Expires: 2026-10-22)' AS
SELECT current_obs.RELEASE_ID, metadata.AS_OF_DATE, current_obs.RESTAURANT_ID,
       roster.RESTAURANT_NAME, roster.MARKET, roster.FORMAT,
       current_obs.BUSINESS_DATE, calendar.BASELINE_DATE, calendar.WEEK_START,
       current_obs.DAYPART, current_obs.CHANNEL,
       roster.OPEN_DATE, roster.CLOSE_DATE,
       CASE WHEN roster.OPEN_DATE > calendar.BASELINE_DATE AND roster.OPEN_DATE <= current_obs.BUSINESS_DATE THEN 'Opening'
            WHEN roster.CLOSE_DATE > calendar.BASELINE_DATE AND roster.CLOSE_DATE <= current_obs.BUSINESS_DATE THEN 'Closure'
            WHEN roster.OPEN_DATE <= calendar.BASELINE_DATE AND (roster.CLOSE_DATE IS NULL OR roster.CLOSE_DATE > current_obs.BUSINESS_DATE) THEN 'Comparable'
            ELSE 'Outside comparison' END AS LIFECYCLE,
       COALESCE(current_obs.COMPLETE AND baseline.COMPLETE AND calendar.COMPLETE, FALSE) AS PAIR_COMPLETE,
       IFF(PAIR_COMPLETE, current_obs.GUESTS, NULL) AS CURRENT_GUESTS,
       IFF(PAIR_COMPLETE, baseline.GUESTS, NULL) AS BASELINE_GUESTS,
       CURRENT_GUESTS - BASELINE_GUESTS AS GUEST_CHANGE,
       IFF(PAIR_COMPLETE, current_obs.CHECKS, NULL) AS CURRENT_CHECKS,
       IFF(PAIR_COMPLETE, baseline.CHECKS, NULL) AS BASELINE_CHECKS,
       IFF(PAIR_COMPLETE, current_obs.NET_SALES, NULL) AS CURRENT_SALES,
       IFF(PAIR_COMPLETE, baseline.NET_SALES, NULL) AS BASELINE_SALES,
       IFF(PAIR_COMPLETE, 0, 1) AS EXCLUDED_PAIRS,
       current_obs.RELEASE_ID || ':' || current_obs.RESTAURANT_ID || ':' || TO_VARCHAR(current_obs.BUSINESS_DATE) || ':' || current_obs.DAYPART || ':' || current_obs.CHANNEL AS EVIDENCE_ID
FROM PERFORMANCE current_obs
JOIN CALENDAR calendar ON current_obs.RELEASE_ID = calendar.RELEASE_ID AND current_obs.BUSINESS_DATE = calendar.BUSINESS_DATE
JOIN ROSTER roster ON current_obs.RELEASE_ID = roster.RELEASE_ID AND current_obs.RESTAURANT_ID = roster.RESTAURANT_ID
JOIN RELEASE_METADATA metadata ON current_obs.RELEASE_ID = metadata.RELEASE_ID
LEFT JOIN PERFORMANCE baseline ON current_obs.RELEASE_ID = baseline.RELEASE_ID
 AND current_obs.RESTAURANT_ID = baseline.RESTAURANT_ID AND calendar.BASELINE_DATE = baseline.BUSINESS_DATE
 AND current_obs.DAYPART = baseline.DAYPART AND current_obs.CHANNEL = baseline.CHANNEL
WHERE calendar.BASELINE_DATE IS NOT NULL;

CREATE OR REPLACE VIEW OPERATIONS_EVIDENCE COPY GRANTS
COMMENT = 'DEMO: All-channel paired operations, one denominator per daypart (Expires: 2026-10-22)' AS
WITH all_channels AS (
 SELECT RELEASE_ID, RESTAURANT_ID, BUSINESS_DATE, BASELINE_DATE, DAYPART,
        COUNT(*) AS CHANNEL_COUNT, SUM(EXCLUDED_PAIRS) AS EXCLUDED_CHANNELS,
        SUM(CURRENT_GUESTS) AS CURRENT_GUESTS, SUM(BASELINE_GUESTS) AS BASELINE_GUESTS
 FROM PAIRED_PERFORMANCE
 GROUP BY RELEASE_ID, RESTAURANT_ID, BUSINESS_DATE, BASELINE_DATE, DAYPART
)
SELECT channels.RELEASE_ID, metadata.AS_OF_DATE, channels.RESTAURANT_ID, roster.RESTAURANT_NAME,
       roster.MARKET, channels.BUSINESS_DATE, channels.BASELINE_DATE, channels.DAYPART,
       COALESCE(channels.CHANNEL_COUNT = 3 AND channels.EXCLUDED_CHANNELS = 0 AND current_ops.COMPLETE AND baseline.COMPLETE, FALSE) AS EVIDENCE_COMPLETE,
       IFF(EVIDENCE_COMPLETE, channels.CURRENT_GUESTS, NULL) AS CURRENT_GUESTS,
       IFF(EVIDENCE_COMPLETE, channels.BASELINE_GUESTS, NULL) AS BASELINE_GUESTS,
       IFF(EVIDENCE_COMPLETE, current_ops.OPEN_HOURS, NULL) AS CURRENT_OPEN_HOURS,
       IFF(EVIDENCE_COMPLETE, baseline.OPEN_HOURS, NULL) AS BASELINE_OPEN_HOURS,
       IFF(EVIDENCE_COMPLETE, current_ops.LABOR_HOURS, NULL) AS CURRENT_LABOR_HOURS,
       IFF(EVIDENCE_COMPLETE, baseline.LABOR_HOURS, NULL) AS BASELINE_LABOR_HOURS,
       IFF(EVIDENCE_COMPLETE, current_ops.SERVICE_MINUTES * current_ops.SERVICE_OBSERVATIONS, NULL) AS CURRENT_SERVICE_TOTAL,
       IFF(EVIDENCE_COMPLETE, current_ops.SERVICE_OBSERVATIONS, NULL) AS CURRENT_SERVICE_COUNT,
       IFF(EVIDENCE_COMPLETE, baseline.SERVICE_MINUTES * baseline.SERVICE_OBSERVATIONS, NULL) AS BASELINE_SERVICE_TOTAL,
       IFF(EVIDENCE_COMPLETE, baseline.SERVICE_OBSERVATIONS, NULL) AS BASELINE_SERVICE_COUNT,
       IFF(EVIDENCE_COMPLETE, 0, 1) AS EXCLUDED_DAYS,
       channels.RELEASE_ID || ':' || channels.RESTAURANT_ID || ':' || TO_VARCHAR(channels.BUSINESS_DATE) || ':' || channels.DAYPART || ':operations' AS EVIDENCE_ID
FROM all_channels channels
JOIN ROSTER roster ON channels.RELEASE_ID = roster.RELEASE_ID AND channels.RESTAURANT_ID = roster.RESTAURANT_ID
JOIN RELEASE_METADATA metadata ON channels.RELEASE_ID = metadata.RELEASE_ID
LEFT JOIN OPERATIONS current_ops ON channels.RELEASE_ID = current_ops.RELEASE_ID AND channels.RESTAURANT_ID = current_ops.RESTAURANT_ID AND channels.BUSINESS_DATE = current_ops.BUSINESS_DATE AND channels.DAYPART = current_ops.DAYPART
LEFT JOIN OPERATIONS baseline ON channels.RELEASE_ID = baseline.RELEASE_ID AND channels.RESTAURANT_ID = baseline.RESTAURANT_ID AND channels.BASELINE_DATE = baseline.BUSINESS_DATE AND channels.DAYPART = baseline.DAYPART;

CREATE OR REPLACE VIEW ANALYSIS_WINDOWS
COMMENT = 'DEMO: Supported frozen peer windows (Expires: 2026-10-22)' AS
SELECT '8 weeks' AS WINDOW_NAME, '2026-07-20'::DATE AS WINDOW_START, '2026-09-14'::DATE AS WINDOW_END
UNION ALL SELECT '4 weeks', '2026-08-17'::DATE, '2026-09-14'::DATE;

CREATE OR REPLACE VIEW PRE_PERIOD_FEATURES
COMMENT = 'DEMO: Pre-period-only matching features (Expires: 2026-10-22)' AS
WITH perf AS (
 SELECT perf.RELEASE_ID, perf.RESTAURANT_ID, windows.WINDOW_NAME, windows.WINDOW_START, windows.WINDOW_END,
        COUNT(*) AS CELLS, COUNT_IF(perf.COMPLETE) AS COMPLETE_CELLS,
        SUM(perf.GUESTS) / 182.0 AS MEAN_DAILY_GUESTS,
        SUM(IFF(perf.DAYPART = 'Breakfast', perf.GUESTS, 0)) / NULLIF(SUM(perf.GUESTS), 0) AS BREAKFAST_MIX,
        SUM(IFF(perf.CHANNEL = 'Delivery', perf.GUESTS, 0)) / NULLIF(SUM(perf.GUESTS), 0) AS DELIVERY_MIX
 FROM PERFORMANCE perf CROSS JOIN ANALYSIS_WINDOWS windows
 WHERE perf.BUSINESS_DATE >= DATEADD(day, -182, windows.WINDOW_START) AND perf.BUSINESS_DATE < windows.WINDOW_START
 GROUP BY perf.RELEASE_ID, perf.RESTAURANT_ID, windows.WINDOW_NAME, windows.WINDOW_START, windows.WINDOW_END
), ops AS (
 SELECT ops.RELEASE_ID, ops.RESTAURANT_ID, windows.WINDOW_NAME,
        COUNT(*) AS DAYS, COUNT_IF(ops.COMPLETE) AS COMPLETE_DAYS, SUM(ops.OPEN_HOURS) / 182.0 AS MEAN_DAILY_OPEN_HOURS
 FROM OPERATIONS ops CROSS JOIN ANALYSIS_WINDOWS windows
 WHERE ops.BUSINESS_DATE >= DATEADD(day, -182, windows.WINDOW_START) AND ops.BUSINESS_DATE < windows.WINDOW_START
 GROUP BY ops.RELEASE_ID, ops.RESTAURANT_ID, windows.WINDOW_NAME
)
SELECT perf.RELEASE_ID, perf.RESTAURANT_ID, roster.RESTAURANT_NAME, roster.MARKET, roster.FORMAT,
       perf.WINDOW_NAME, perf.WINDOW_START, perf.WINDOW_END,
       perf.MEAN_DAILY_GUESTS, perf.BREAKFAST_MIX, perf.DELIVERY_MIX, ops.MEAN_DAILY_OPEN_HOURS
FROM perf JOIN ops ON perf.RELEASE_ID = ops.RELEASE_ID AND perf.RESTAURANT_ID = ops.RESTAURANT_ID AND perf.WINDOW_NAME = ops.WINDOW_NAME
JOIN ROSTER roster ON perf.RELEASE_ID = roster.RELEASE_ID AND perf.RESTAURANT_ID = roster.RESTAURANT_ID
WHERE perf.CELLS = 2184 AND perf.COMPLETE_CELLS = 2184 AND ops.DAYS = 728 AND ops.COMPLETE_DAYS = 728
 AND roster.OPEN_DATE <= DATEADD(day, -182, perf.WINDOW_START)
 AND (roster.CLOSE_DATE IS NULL OR roster.CLOSE_DATE >= perf.WINDOW_START);

CREATE OR REPLACE VIEW PEER_SELECTION COPY GRANTS
COMMENT = 'DEMO: Frozen pre-period peers, not causal controls (Expires: 2026-10-22)' AS
SELECT focal.RELEASE_ID, focal.RESTAURANT_ID, focal.WINDOW_NAME, focal.WINDOW_START, focal.WINDOW_END,
       peer.RESTAURANT_ID AS PEER_ID, peer.MARKET AS PEER_MARKET,
       IFF(focal.MARKET = peer.MARKET, 'Within market', 'Across markets') AS PEER_SCOPE,
       0.4 * ABS(focal.MEAN_DAILY_GUESTS - peer.MEAN_DAILY_GUESTS) / 50.0
       + 0.2 * ABS(focal.BREAKFAST_MIX - peer.BREAKFAST_MIX) / 0.05
       + 0.2 * ABS(focal.DELIVERY_MIX - peer.DELIVERY_MIX) / 0.05
       + 0.2 * ABS(focal.MEAN_DAILY_OPEN_HOURS - peer.MEAN_DAILY_OPEN_HOURS) / 3.0 AS DISTANCE,
       ROW_NUMBER() OVER (PARTITION BY focal.RELEASE_ID, focal.RESTAURANT_ID, focal.WINDOW_NAME, PEER_SCOPE ORDER BY DISTANCE, peer.RESTAURANT_ID) AS PEER_RANK
FROM PRE_PERIOD_FEATURES focal JOIN PRE_PERIOD_FEATURES peer
 ON focal.RELEASE_ID = peer.RELEASE_ID AND focal.WINDOW_NAME = peer.WINDOW_NAME AND focal.FORMAT = peer.FORMAT AND focal.RESTAURANT_ID <> peer.RESTAURANT_ID
WHERE DISTANCE <= 1.0
QUALIFY PEER_RANK <= 5;

CREATE OR REPLACE VIEW WINDOW_OUTCOMES
COMMENT = 'DEMO: Paired restaurant outcomes, whole-window lifecycle (Expires: 2026-10-22)' AS
SELECT perf.RELEASE_ID, perf.RESTAURANT_ID, perf.RESTAURANT_NAME, perf.MARKET,
       windows.WINDOW_NAME, windows.WINDOW_START, windows.WINDOW_END,
       SUM(perf.CURRENT_GUESTS) AS CURRENT_GUESTS, SUM(perf.BASELINE_GUESTS) AS BASELINE_GUESTS,
       SUM(perf.GUEST_CHANGE) AS GUEST_CHANGE, SUM(perf.EXCLUDED_PAIRS) AS EXCLUDED_PAIRS,
       COUNT(*) AS EXPECTED_PAIRS, COUNT_IF(perf.LIFECYCLE <> 'Comparable') AS NONCOMP_PAIRS,
       100.0 * SUM(perf.GUEST_CHANGE) / NULLIF(SUM(perf.BASELINE_GUESTS), 0) AS CHANGE_PCT
FROM PAIRED_PERFORMANCE perf CROSS JOIN ANALYSIS_WINDOWS windows
WHERE perf.BUSINESS_DATE >= windows.WINDOW_START AND perf.BUSINESS_DATE < windows.WINDOW_END
GROUP BY perf.RELEASE_ID, perf.RESTAURANT_ID, perf.RESTAURANT_NAME, perf.MARKET, windows.WINDOW_NAME, windows.WINDOW_START, windows.WINDOW_END;

CREATE OR REPLACE VIEW COMPARISON_EVIDENCE COPY GRANTS
COMMENT = 'DEMO: Descriptive gaps withheld for incomplete selected peers (Expires: 2026-10-22)' AS
WITH peers AS (
 SELECT selection.RELEASE_ID, selection.RESTAURANT_ID, selection.WINDOW_NAME, selection.PEER_SCOPE,
        COUNT(*) AS PEER_COUNT,
        COUNT_IF(outcome.EXCLUDED_PAIRS = 0 AND outcome.NONCOMP_PAIRS = 0 AND outcome.BASELINE_GUESTS > 0) AS VALID_PEER_COUNT,
        AVG(outcome.CHANGE_PCT) AS PEER_CHANGE_PCT,
        AVG(IFF(selection.PEER_RANK <= 3, outcome.CHANGE_PCT, NULL)) AS TOP3_CHANGE_PCT,
        LISTAGG(selection.PEER_ID, ', ') WITHIN GROUP (ORDER BY selection.PEER_RANK) AS PEER_IDS,
        MAX(selection.DISTANCE) AS MAX_DISTANCE
 FROM PEER_SELECTION selection LEFT JOIN WINDOW_OUTCOMES outcome
  ON selection.RELEASE_ID = outcome.RELEASE_ID AND selection.PEER_ID = outcome.RESTAURANT_ID AND selection.WINDOW_NAME = outcome.WINDOW_NAME
 GROUP BY selection.RELEASE_ID, selection.RESTAURANT_ID, selection.WINDOW_NAME, selection.PEER_SCOPE
), scopes AS (SELECT 'Within market' AS PEER_SCOPE UNION ALL SELECT 'Across markets')
SELECT outcome.RELEASE_ID, outcome.RESTAURANT_ID, outcome.RESTAURANT_NAME, outcome.MARKET,
       outcome.WINDOW_NAME, outcome.WINDOW_START, outcome.WINDOW_END, scopes.PEER_SCOPE,
       outcome.CURRENT_GUESTS, outcome.BASELINE_GUESTS, outcome.GUEST_CHANGE, outcome.EXCLUDED_PAIRS,
       outcome.CHANGE_PCT AS FOCAL_CHANGE_PCT, COALESCE(peers.PEER_COUNT, 0) AS PEER_COUNT,
       peers.PEER_IDS, peers.MAX_DISTANCE,
       CASE WHEN outcome.EXCLUDED_PAIRS > 0 THEN 'Incomplete focal observations'
            WHEN outcome.NONCOMP_PAIRS > 0 THEN 'Focal lifecycle change'
            WHEN COALESCE(peers.PEER_COUNT, 0) < 3 THEN 'Insufficient pre-period peers'
            WHEN peers.VALID_PEER_COUNT <> peers.PEER_COUNT THEN 'Selected peer incomplete or lifecycle-changing'
            WHEN outcome.BASELINE_GUESTS = 0 THEN 'Zero focal baseline'
            ELSE 'Available' END AS GAP_STATUS,
       IFF(GAP_STATUS = 'Available', peers.PEER_CHANGE_PCT, NULL) AS PEER_CHANGE_PCT,
       IFF(GAP_STATUS = 'Available', outcome.CHANGE_PCT - peers.PEER_CHANGE_PCT, NULL) AS GAP_PP,
       IFF(GAP_STATUS = 'Available', outcome.CHANGE_PCT - peers.TOP3_CHANGE_PCT, NULL) AS TOP3_GAP_PP,
       'pre26-v3' AS PEER_POLICY,
       outcome.RELEASE_ID || ':' || outcome.RESTAURANT_ID || ':' || outcome.WINDOW_NAME || ':' || scopes.PEER_SCOPE AS EVIDENCE_ID
FROM WINDOW_OUTCOMES outcome CROSS JOIN scopes
LEFT JOIN peers ON outcome.RELEASE_ID = peers.RELEASE_ID AND outcome.RESTAURANT_ID = peers.RESTAURANT_ID AND outcome.WINDOW_NAME = peers.WINDOW_NAME AND scopes.PEER_SCOPE = peers.PEER_SCOPE;