USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS SFE_RESTAURANT_RECOVERY_READER
  COMMENT = 'DEMO: Restaurant recovery serving access (Expires: 2026-10-22)';
GRANT ROLE SFE_RESTAURANT_RECOVERY_READER TO ROLE SYSADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE SFE_RESTAURANT_RECOVERY_READER;
GRANT USAGE ON DATABASE SNOWFLAKE_EXAMPLE TO ROLE SFE_RESTAURANT_RECOVERY_READER;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY TO ROLE SFE_RESTAURANT_RECOVERY_READER;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS TO ROLE SFE_RESTAURANT_RECOVERY_READER;
GRANT USAGE ON WAREHOUSE SFE_RESTAURANT_RECOVERY_WH TO ROLE SFE_RESTAURANT_RECOVERY_READER;
GRANT USAGE ON AGENT SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.RESTAURANT_RECOVERY_AGENT TO ROLE SFE_RESTAURANT_RECOVERY_READER;
GRANT SELECT, REFERENCES ON SEMANTIC VIEW SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_RESTAURANT_RECOVERY_PERFORMANCE TO ROLE SFE_RESTAURANT_RECOVERY_READER;
GRANT SELECT, REFERENCES ON SEMANTIC VIEW SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_RESTAURANT_RECOVERY_OPERATIONS TO ROLE SFE_RESTAURANT_RECOVERY_READER;
GRANT SELECT, REFERENCES ON SEMANTIC VIEW SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_RESTAURANT_RECOVERY_COMPARISONS TO ROLE SFE_RESTAURANT_RECOVERY_READER;
GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.PAIRED_PERFORMANCE TO ROLE SFE_RESTAURANT_RECOVERY_READER;
GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.OPERATIONS_EVIDENCE TO ROLE SFE_RESTAURANT_RECOVERY_READER;
GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.COMPARISON_EVIDENCE TO ROLE SFE_RESTAURANT_RECOVERY_READER;
GRANT READ ON STAGE SNOWFLAKE_EXAMPLE.RESTAURANT_RECOVERY.RELEASE_FILES TO ROLE SFE_RESTAURANT_RECOVERY_READER;
USE ROLE SYSADMIN;